### ISSUE TITLE
Keybind

### ISSUE THREAD

**Issue by ardissaps** [Prospector/ModMenu#445] opened 2022-06-10 05:39 UTC
Like lets press F9 in game to open modmenu directly (this will increase mouse click lifespan probably) :D

**Comment by MagnusHJensen** [comment] 2022-06-10 05:49
See #444

**Comment by ardissaps** [comment] 2022-06-10 05:52
> See #444

Does that mean it will be added in the future? Sorry I can't understand programming language that much

**Comment by jackassmc** [comment] 2022-06-10 11:01
Duplicate of https://github.com/TerraformersMC/ModMenu/issues/403 and implemented for 1.18 in https://github.com/TerraformersMC/ModMenu/pull/444.

That means that this feature was already requested in https://github.com/TerraformersMC/ModMenu/issues/403 and will be added for 1.18 in https://github.com/TerraformersMC/ModMenu/pull/444.

**Closed as duplicate by jackassmc** 2022-06-10 11:01 UTC

**Comment by ardissaps** [comment] 2022-06-10 12:02
> Duplicate of #403 and implemented for 1.18 in #444.
> 
> That means that this feature was already requested in #403 and will be added for 1.18 in #444.

Ah I see, I understand now. Thank you very much.
