### ISSUE TITLE
update icon showing for hidden mods

### ISSUE THREAD

**Issue by dbrighthd** [Prospector/ModMenu#589] opened 2023-04-05 02:44 UTC
I have "Libararies" hidden, and when Fabric API had an update available it showed the icon but I could not find the mod that needed updating (because it was hidden)

Maybe it would be useful to show a hidden mod in the list when there is an update available for it, or not show the icon when the only mods that have an update are hidden in the list?
![image](https://user-images.githubusercontent.com/68525639/229967727-592508d1-19b2-45ef-80fb-65bcf6214c3e.png)

**Comment by haykam821** [comment] 2023-07-09 17:49
Duplicate of #553

**Closed as not planned by haykam821** 2023-07-09 17:49 UTC
Labels: bug
