### ISSUE TITLE
[Suggestion] Add the functionality to "activate" and "de-activate" mods

### ISSUE THREAD

**Issue by Eiion** [Prospector/ModMenu#255] opened 2021-05-10 19:55 UTC
Having to drag out and back in mods when we do or don't need them can get annoying. How about adding a feature to your mod that not only allows as to take a look at all the mods currently running but also to select which of them should run and which shouldn't.

Maybe this could be done by automatically changing certain parts of the mods' code to remarks or by temporarily renaming the mods file format (to make them not work upon restart) or by telling the game to ignore certain files... I really don't know, I'm just blindly guessing as I'm not a coder. So I don't know if this would technically even be possible and if so, how. I just wanted to suggest it for you to consider possibly adding it.

**Comment by K0-RR** [comment] 2021-05-10 20:33
This could be done like they did it in MultiMC - you can (de)select a mod and it gets renamed to *.jar.disabled so it's not loaded on the next start.

**Comment by Eiion** [comment] 2021-05-11 09:15
So I actually was on the right way with my suggestion on how to possibly implement it.

I hope the addition of the feature is welcome by the mod's creators and someone finds the time to add what's necessary.

**Comment by jackassmc** [comment] 2021-08-27 02:02
This is a duplicate of https://github.com/TerraformersMC/ModMenu/issues/155.

**Closed as completed by jackassmc** 2021-08-27 02:02 UTC
Labels: enhancement
