### ISSUE TITLE
[1.18.2] Getting Log Errors (jdk.nio.zipfs.ZipFileSystem.newInputStream)

### ISSUE THREAD

**Issue by pewblaze** [Prospector/ModMenu#408] opened 2022-04-04 19:11 UTC
Hi, im getting Errors in my log.

```
java.nio.file.NoSuchFileException: /assets/seedfix/icon.png
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at jdk.nio.zipfs.ZipFileSystem.newInputStream(ZipFileSystem.java:856) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipPath.newInputStream(ZipPath.java:749) ~[jdk.zipfs:?]
	at jdk.nio.zipfs.ZipFileSystemProvider.newInputStream(ZipFileSystemProvider.java:261) ~[jdk.zipfs:?]
	at java.nio.file.Files.newInputStream(Files.java:160) ~[?:?]
	at com.terraformersmc.modmenu.util.mod.ModIconHandler.createIcon(ModIconHandler.java:33) ~[modmenu-3.1.0.jar:?]
	at com.terraformersmc.modmenu.util.mod.fabric.FabricMod.getIcon(FabricMod.java:141) ~[modmenu-3.1.0.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.bindIconTexture(ModListEntry.java:97) ~[modmenu-3.1.0.jar:?]
	at com.terraformersmc.modmenu.gui.widget.entries.ModListEntry.render(ModListEntry.java:53) ~[modmenu-3.1.0.jar:?]
	at com.terraformersmc.modmenu.gui.widget.ModListWidget.renderList(ModListWidget.java:227) ~[modmenu-3.1.0.jar:?]
	at net.minecraft.client.gui.widget.EntryListWidget.render(EntryListWidget:219) ~[?:?]
	at com.terraformersmc.modmenu.gui.ModsScreen.render(ModsScreen.java:280) ~[modmenu-3.1.0.jar:?]
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:877) ~[?:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:737) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:236) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
```

Not sure whats happening or why that happens ^^"?
The game isnt crashin or anything, but i get some lags & im trying to pin them down ^^"

[latest.log](https://github.com/TerraformersMC/ModMenu/files/8412485/latest.log)

**Comment by jackassmc** [comment] 2022-05-09 08:49
This is somewhat related to https://github.com/TerraformersMC/ModMenu/issues/363, if the icon was cached it wouldn't spam the log with exceptions. Not Enough Crashes deobfuscating the exception might cause the lag.

**Comment by jackassmc** [comment] 2022-05-09 08:53
Actually this is a duplicate of #363 so I'm closing this.

**Closed as duplicate by jackassmc** 2022-05-09 08:53 UTC
