### ISSUE TITLE
Game Crashing upon clicking 'Mod' on title screen

### ISSUE THREAD

**Issue by Mashmello6** [Prospector/ModMenu#593] opened 2023-04-15 00:56 UTC
When I install ModMenu and put it into the mods folder, as soon as I launch Minecraft (under the fabric launcher) and click the 'Mods' button on the title screen it crashes and yields this crash report;

[crash-2023-04-15_10.49.00-client.txt](https://github.com/TerraformersMC/ModMenu/files/11237951/crash-2023-04-15_10.49.00-client.txt)

Thanks for the help!

**Comment by haykam821** [comment] 2023-04-15 01:04
This issue is a duplicate of TerraformersMC/ModMenu#580. You are using a version of Mod Menu that is not compatible with Minecraft 1.19.4.

**Closed as not planned by haykam821** 2023-04-15 01:04 UTC
