### ISSUE TITLE
Crash on 1.16 release

### ISSUE THREAD

**Issue by Minenash** [Prospector/ModMenu#122] opened 2020-06-23 17:20 UTC
On a fresh copy of Minecraft 1.16 with the latest Fabric API and the 1.16 release of ModMenu

The main error:
>Critical injection failure: @ModifyArg annotation on adjustRealmsHeight could not find any targets matching 'Lnet/minecraft/class_442;method_25426()V'

[Full Crash Log](https://hastebin.com/jirofikisu.log)

**Comment by Prospector** [comment] 2020-07-12 07:49
Does this still happen? I never was able to reproduce.

**Comment by DahliaSR** [comment] 2020-07-12 15:12
Yes, this still happens with MC 1.16.1 and latest versions of Fabric, Fabric API and ModMenu.

I tested it without any other mod, so it must be ModMenu.

**Comment by Minenash** [comment] 2020-07-12 15:15
That's interesting, because it works fine for me on 1.16.1. When I can get to my pc I was going to test if this happened on the original 1.16 release or the re-release

**Comment by Prospector** [comment] 2020-07-12 23:08
I cannot reproduce. ![image](https://user-images.githubusercontent.com/6166773/87258628-e917b580-c459-11ea-9f1c-5863103daa9c.png)

Can you send a log @DahliaSR?

**Comment by DahliaSR** [comment] 2020-07-14 16:42
hey, @Prospector.

I found the issue.
It was messed up itermediary mappings on my client.
A fresh install again - a bit different than before - and it works perfectly fine.

So from POV this can be closed.

**Comment by Prospector** [comment] 2020-07-14 19:26
Ah, good to hear! I'm pretty sure the original issue this report was about was related to mojang re-releasing 1.16 with the same version but with Realms changes, so I shall close this.

**Closed as completed by Prospector** 2020-07-14 19:26 UTC
Labels: unverified
