### ISSUE TITLE
Mods button can't be clicked on title screen with MineTogether 1.18

### ISSUE THREAD

**Issue by cannon9009** [Prospector/ModMenu#390] opened 2022-02-02 00:09 UTC
![image](https://user-images.githubusercontent.com/70039616/152072230-df1b194e-9e65-462e-8cab-113e022a14b4.png)

Not entirely sure what's wrong; I have another fabric profile that doesn't have this issue. I'll post my log here...

[latest.log](https://github.com/TerraformersMC/ModMenu/files/7982705/latest.log)

**Comment by jackassmc** [comment] 2022-02-02 00:48
This is probably caused by one of your mods. Please post your `modmenu.json` file and try removing mods until the issue is resolved. Since you have a lot of mods enabled it might be faster to first compare the mods to the profile that doesn't have this problem and start disabling the mods not in that profile.

Are you using a modpack?

**Comment by cannon9009** [comment] 2022-02-02 01:20
I'm very truly sorry, I accidentally deleted the profile that had this issue. Very sorry for the trouble but I didn't manage to save a backup for the list. Not sure how to recover it.

**Comment by jackassmc** [comment] 2022-02-02 07:24
No problem, but since this issue can't be reproduced I'm closing this issue.

If you happen to come across this bug again please reopen this issue and we will identify the mod that is causing it.

**Comment by cannon9009** [comment] 2022-02-02 17:58
> No problem, but since this issue can't be reproduced I'm closing this issue.
> 
> If you happen to come across this bug again please reopen this issue and we will identify the mod that is causing it.

Hey, I'm back! It happened again, thankfully I'm able to get this sorted out now. [Here's my log, with the modlist at the top.](https://pastebin.com/aNbqnFWF)
I'm not sure how to reopen issues, but here's hoping you see this.

**Comment by jackassmc** [comment] 2022-02-02 19:31
Okay, let's figure out which mod is causing this.
But first please post your `modmenu.json` file, it's located at `.minecraft/config/modmenu.json`.

To identify which mod is causing this problem you need to remove mods that aren't causing it until the broken mod is found:
1. Make a backup of your Minecraft instance
2. Remove half of the mods
    - If the problem still happens keep repeating step 2
    - If the problem is fixed readd the mods you have just removed and remove the other half of the mods instead, then keep repeating step 2
3. Once you can't remove any more mods without fixing the problem post another log

**Comment by cannon9009** [comment] 2022-02-02 20:26
[Here's modmenu.json.](https://pastebin.com/peXb7HSx) I'll get to finding the problem right away.

**Comment by cannon9009** [comment] 2022-02-03 01:37
Ding dong! I found a troublemaker! MineTogether seems to cause this issue. I believe this might be the only one, but I'll keep searching through the modlist to see if anything else causes problems.

**Comment by cannon9009** [comment] 2022-02-03 02:28
Looks like everything else is okay. Only MineTogether was causing a problem with the button.

**Comment by jackassmc** [comment] 2022-02-03 07:20
Well done! Thanks to your efforts this bug will likely get fixed during the alpha of MineTogether 1.18!

I can confirm bad button placement in 1.18 with ModMenu 3.0.1 and MineTogether 1.18 Alpha.

Please post a bug report to the [MineTogether repo](https://github.com/CreeperHost/MineTogether). You can link them to the ModMenu code that creates the mod button on the title screen [here](https://github.com/TerraformersMC/ModMenu/blob/697a85727ddac9d4c99a94f090ffdb6479610371/src/main/java/com/terraformersmc/modmenu/event/ModMenuEventHandler.java#L37-L77) and tell them that it relies on the Realms button.

**Comment by jackassmc** [comment] 2022-02-03 08:41
To work around this problem unit it is fixed the "Below Realms" mod button setting seems to work.

To access Mod Menu while not being able to click the mods button on the title screen these are the possibilities:
- Open the Mod Menu through the pause menu instead
- Use the tab key to select the mods button (white border) and then press the enter key to open it

**Closed as completed** 2022-06-11 16:49 UTC
Labels: bug, mod compat
