### ISSUE TITLE
crash when attempting to open game menu

### ISSUE THREAD

**Issue by alien-sunset** [Prospector/ModMenu#757] opened 2024-07-05 17:18 UTC
this only happens when I have Mod Menu installed
hitting escape to open the game menu results in a crash:
minecraft 1.21
Mod Menu 11.0.1

crash report:
https://mclo.gs/A3L2KPP

**Comment by ghost** [comment] 2024-07-05 19:22
Hi, I had a similar crash but turns out it was actually a different mod causing the crash, once i removed that one mod menu didn't crash my game anymore. (the mod for me causing the crash was VersionChanger)

Try removing some of your mods to find out which one is causing it.

**Comment by alien-sunset** [comment] 2024-07-06 19:41
hmm, I don't have version changer, but i do have via version, I can't test it tonight, but I'll try it out tomorrow and see how that goes.

although, if it does have to do with viaversion, then while it's a different mod to yours, it still serves a similar purpose, and I would think it would still be a modmeanu issue: some sort of incompatibility with how those mods jigger around some of the back end stuff, and still worth a look

**Comment by TheCaJlaT** [comment] 2024-07-07 08:31
Same crash at ModMenu v11.0.1 and v.11.0.0 https://mclo.gs/W6tqhj1

**Comment by Hmzn14** [comment] 2024-07-09 09:53
> Same crash at ModMenu v11.0.1 and v.11.0.0 https://mclo.gs/W6tqhj1

Had the exact same crash anyone got a fix?

Expected: [Lnet/minecraft/class_7845;, Lnet/minecraft/class_7845$class_7939;, Lnet/minecraft/class_2561;]
    Found: [Lnet/minecraft/class_7845;, Lnet/minecraft/class_7845$class_7939;, Lnet/minecraft/class_9782;]
Available: [Lnet/minecraft/class_7845;, Lnet/minecraft/class_7845$class_7939;, Lnet/minecraft/class_9782;, Lnet/minecraft/class_2561;]

**Comment by liangmiQwQ** [comment] 2024-07-09 12:53
The same bug, If unload ModMenu, the game will run normally

**Comment by alien-sunset** [comment] 2024-07-09 22:34
finally got a chance to test, and it wasn't ViaFabricPlus (I was mistaken on which mod I was using) I still crashed when trying to open the game menu with it removed. so def something going on with ModMenu itself

**Comment by sakura-ryoko** [comment] 2024-07-10 20:09
Can you post a new crash log without ViaFabric?  I just want to see the same error
`callback mixins.modmenu.json:MixinGameMenu`

**Comment by alien-sunset** [comment] 2024-07-10 23:53
here's one from tonight, no ViaFabricPlus

[9xpgE3S.txt](https://github.com/user-attachments/files/21930518/9xpgE3S.txt)

**Comment by sakura-ryoko** [comment] 2024-07-11 04:35
Yeah so the relevant lines are:
```
org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_433::method_20543()V has incompatible changes at opcode 239 in callback mixins.modmenu.json:MixinGameMenu from mod modmenu->@Inject::onInitWidgets(Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_7845;Lnet/minecraft/class_7845$class_7939;Lnet/minecraft/class_2561;)V.
net.minecraft.client.gui.screen.GameMenuScreen.initWidgets(GameMenuScreen.java:120)
```
Which I have not seen this looking at the code at all, and the mixin should work as expected, IMO.
Perhaps something else is messing with the GameMenu that isn't Mod Menu, such as a Launcher issue.

It seems to be related to the attempt at capturing Local Variables.

**Comment by alien-sunset** [comment] 2024-07-11 18:15
welp, now I'm confused as heck,

I started doing a binary search to figure out which of my other mods was causing the conflict.... and now it's working perfectly.
I have ALL of the mods running that I was running when previously experiencing the crash and I am no longer crashing.

I have no idea what is going on
(advancement Info reloaded did update last night, (and I also added Replay Mod,) so maybe it was advancement info reloaded and the update fixed whatever the problem was, idek, but it's working now and my head hurts )

**Comment by sakura-ryoko** [comment] 2024-07-11 22:45
GG

**Comment by FakeDomi** [comment] 2024-08-05 19:25
This is caused by https://github.com/TerraformersMC/ModMenu/blob/1.21/src/main/java/com/terraformersmc/modmenu/mixin/MixinGameMenu.java#L31 when another mod's mixin causes a change to the local variables.

You should still see the error in the log, even if it doesn't crash the game.

It can be fixed by rewriting the ModMenu mixin, or by changing the priority in the other mod's mixin to make it apply later.
Edit: nvm, it doesn't even use the remaining locals. Easy fix in ModMenu then.

**Closed as completed** 2024-08-25 16:43 UTC
