### ISSUE TITLE
Crash trying to load v7.2.1 into 1.20.2-pre2

### ISSUE THREAD

**Issue by vico93** [Prospector/ModMenu#653] opened 2023-09-08 02:39 UTC
Just to clarify, i know ModMenu doesn't have an official build for 1.20.2-preX yet, but i tried to load it to see if the changes in vanilla would affect or not the mod, and if positive to gather the crash report to see if this would be of any use by your guys.

[Here's the crash i had.](https://gist.github.com/vico93/bb9b2d964236a22b4c72b3527f29155a)

I hope this can be of use on the process of updating the mod to 1.20.2!

**Comment by haykam821** [comment] 2023-09-08 02:43
Have you tried #649? There are many issues caused by GUI textures being split out of manual atlases that are resolved by that pull request.

**Comment by vico93** [comment] 2023-09-08 02:45
> Have you tried #649? There are many issues caused by GUI textures being split out of manual atlases that are resolved by that pull request.

oh i will try that right now! didn't saw that pr yet

**Comment by vico93** [comment] 2023-09-08 02:50
Worked!
![2023-09-07_23 48 50](https://github.com/TerraformersMC/ModMenu/assets/3485505/53f195ce-69fb-486a-8d87-a7a04e9dead0)
[Relevant latest.log](https://gist.github.com/vico93/01cec9a845016c57a10915e8bb2bfcfc)

**Closed as completed** 2023-12-03 19:24 UTC
