### ISSUE TITLE
Crash with new 1.16.20 update

### ISSUE THREAD

**Issue by Bobbry** [Prospector/ModMenu#346] opened 2021-09-26 20:51 UTC
Attempting to load into the game results in an instant crash.
Log here: https://pastebin.com/g1WRNc7L

**Comment by GeoGenius4210** [comment] 2021-09-26 21:07
Yeah, I got the same problem as you.
here's my log: [https://pastebin.com/tFDA2pa0](url)
my mods:
![image](https://user-images.githubusercontent.com/74439774/134824197-2093e588-7907-46d9-9d40-8a65242fe960.png)

**Comment by Romz24** [comment] 2021-09-26 21:26
My game crashes too. I came here to write about this error, but I see that you are ahead of me.

**Comment by GeoGenius4210** [comment] 2021-09-26 21:48
I fixed the issue by using the second most recent version.

**Comment by jackassmc** [comment] 2021-09-27 02:23
Thank you all for your reports! This issue has been resolved in Mod Menu v1.16.21.

The root cause of the crash was that I carelessly used a Java 9 feature in Mod Menu for Minecraft 1.16 (which supports Java 8 and up). Usually this would have been caught during CI but I also recently removed Java 8 builds because they just stopped working all by themselves. Today I found out that this was caused by a dependency of Fabric Loom dropping support for Java 8 but that this was fixed in newer Loom versions. So I updated Loom and re-enabled Java 8 builds, ensuring that similar problems won't make it into a release in the future.

**Closed as completed by jackassmc** 2021-09-27 02:23 UTC
