### ISSUE TITLE
Culling too early

### ISSUE THREAD

**Issue by TheKodeToad** [Prospector/ModMenu#575] opened 2023-03-13 22:32 UTC
More text should be visible in the description!

![image](https://user-images.githubusercontent.com/57493648/224847154-04566ec2-9852-42b8-b75e-13e27ab876f4.png)

**Comment by haykam821** [comment] 2023-03-13 22:49
Duplicate of #532

**Closed as not planned by haykam821** 2023-03-13 22:49 UTC

**Comment by TheKodeToad** [comment] 2023-03-13 23:10
Ahh, sorry. I couldn't find anything with "culling".
