### ISSUE TITLE
bug on newest version

### ISSUE THREAD

**Issue by catvin82** [Prospector/ModMenu#629] opened 2023-07-16 02:02 UTC
![image](https://github.com/TerraformersMC/ModMenu/assets/96541972/c7b0a9eb-43a7-4e2f-92ba-7fbb03314744)

I usually play on 1.19 and found this bug when updating mod menu. I work with a bunch of other mods that could be causing the problem, but downgrading mod menu worked for 1.19.4. Now I am updating my huge modpack to 1.20.1 and the error shows again, but this time I can't downgrade the mod. 

mods: 
![I'm too lazy to type them all out](https://github.com/TerraformersMC/ModMenu/assets/96541972/9d1bf006-cbdf-4f0e-9304-5c4973f6634f)
I'm too lazy to type them all out

Ask for any information needed.
Sys info:
GNU/Linux
Kernel Linux 6.3.8-200.fc38.x86_64
OS
Fedora Linux 38
Wayland
x64_86
Gnome 44.2
Computer
16 gb ram
AMD Ryzen™ 5 5600G with Radeon™ Graphics × 12
AMD Radeon™ Graphics

**Comment by haykam821** [comment] 2023-07-16 08:05
This issue is a duplicate of #607, and the issue has already been solved in [version 7.1.0](https://github.com/TerraformersMC/ModMenu/releases/tag/v7.1.0). The version you are using is outdated.

**Closed as not planned by haykam821** 2023-07-16 08:05 UTC
